
# Raw data files
dgrp2-location: "resources/dgrp2.vcf.gz"
jiggins-data: "resources/jiggins-data.txt"

# Summary statistic normalization boundaries
stats-file-location: "resources/normalization-stats.tsv"

# Programs that you can't install easily with conda
beagle-location: "bin/beagle.28Jun21.220.jar"
