# Change this to work on the cluster or not.
# workdir: "/fs/cbsuclarkfs1/storage/ivc2/drosophila-sweeps"

# Directory where all the simulation files are supposed to be
raw_sim_folder: "raw-simulations"

# Simulation identifiers that we are interested in:
sim_folders:
  - simtest-15

