
raw_sim_folder: "raw-simulations/20211004_simulations"
epochs_for_model_training: 25
num_overfitting_replicates: 10
epochs_for_overfitting_analyses: 60

validation_percentage: 0.2

sims_per_regime: 5000

training_ids:
  - main-fixedsweeps
  - main-partialsweeps

testing_ids:
  - bottleneck-1percent
  - bottleneck-5percent
  - offcenter-10000bp
  - offcenter-500bp
  - popsize-higher
  - popsize-lower
  - recombination-higher
  - recombination-lower

inference_targets:
  - log-sel-strength
  - sweep-mode
  - hard-vs-soft
  - rnm-vs-sgv
