
raw_sim_folder: "raw-simulations/20211004_simulations"
num_overfitting_replicates: 10

validation_percentage: 0.2

training_ids:
  - main-fixedsweeps
  - main-partialsweeps
testing_ids:
  - bottleneck-1percent
  - bottleneck-5percent
  - offcenter-10000bp
  - offcenter-500bp
  - popsize-higher
  - popsize-lower
  - recombination-higher
  - recombination-lower

inference_targets:
  - log-sel-strength
  - sweep-mode
  - hard-vs-soft
  - rnm-vs-sgv
